name = "am-here"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "420fa87ce1da4481b380ef6e2ede8add"
preview_id = "420fa87ce1da4481b380ef6e2ede8add"

[env.production]
name = "am-here"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "production_id"

[env.staging]
name = "am-here-staging"

[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "staging_id"